### ISSUE TITLE
Elem.render doesn't empty node before render in some case

### ISSUE THREAD

**Issue by ybonnel** [mathieuancelin/elem-vdom#11]
http://jsfiddle.net/91s5an6n/

This case works very well with old elem.

**Comment by ybonnel** [comment]
Same sample with old elem : 
http://jsfiddle.net/gfostw7r/

**Comment by mathieuancelin** [comment]
Yep, you're not supposed to render inside an actual Elem tree. It's an anti pattern because by doing that you're messing up the diffing system of elem-vdom. A tree should be handled only by itself.

But you can use `Elem.unmount` before a render to do it.

http://jsfiddle.net/91s5an6n/2/

**Comment by ybonnel** [comment]
Maybe we need two render fonctions. (I think about portaljs and his widgets)

Le mer. 12 août 2015 18:55, Mathieu ANCELIN notifications@github.com a
écrit :

**Comment by mathieuancelin** [comment]
Should be better now

**Comment by ybonnel** [comment]
The first jsfiddle works

Le mer. 12 août 2015 19:51, Mathieu ANCELIN notifications@github.com a
écrit :
