### ISSUE TITLE
Better function render with elem

### ISSUE THREAD

**Issue by ybonnel** [mathieuancelin/elem-vdom#9]
In older version of elem we could use :

```
  Elem.render([elements], node);
```

This doesn't work with elem-vdom.

So if I want something like :

```
  <div>1</div>
  <div>2</div>
```

Before (with elem) :

```
  Elem.render(
    [
      Elem.el('div', {},  '1'),
      Elem.el('div', {},  '2')
    ],
   node
  );
```

Now (with elem-vdom) : 

```
  Elem.render(
    Elem.el('div', {}, [
      Elem.el('div', {},  '1'),
      Elem.el('div', {},  '2')
    ]),
   node
  );
```

I must create a useless intermediate node.

**Comment by ybonnel** [comment]
Sample of the problem : 
http://jsfiddle.net/6f6o9n0a/

**Comment by mathieuancelin** [comment]
Yep, it's a feature actually :-) 

You need a unique root element in order to make virtual-dom work.

I can automatically add a span wrapper if you like

**Comment by ybonnel** [comment]
I think you have a root element, it 's the second parameter the function ;)

Le mer. 12 août 2015 19:00, Mathieu ANCELIN notifications@github.com a
écrit :

**Comment by mathieuancelin** [comment]
What I meant was you can't render multiples element at the root level (an array) you need to wrap it in another element. 

It's 'fixed' in 6875062387584e04376cd5c59432fbf634b1c13f, meaning, I wrap the array in a span.

**Comment by ybonnel** [comment]
You can't use parent node has root element for your virtual dom?

Le mer. 12 août 2015 19:21, Mathieu ANCELIN notifications@github.com a
écrit :

**Comment by mathieuancelin** [comment]
No, the actual dom can't be used for that

**Comment by ybonnel** [comment]
You can't create a root element only virtual witch Will not be render ?

Le mer. 12 août 2015 20:02, Mathieu ANCELIN notifications@github.com a
écrit :

**Comment by mathieuancelin** [comment]
With virtual-dom the only way to create the DOM tree corresponding to a VNode tree (the entry point that can be diff. later) is throught the function `createElement`.
And `createElement` only takes one VNode as param : 

https://github.com/Matt-Esch/virtual-dom/blob/master/vdom/create-element.js#L22
